workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    scripts:
      - name: Build Android app
        script: 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
